#! /bin/sh
# /etc/init.d/volumioLCDservice
#

# Some things that run always
touch /var/lock/volumioLCDservice

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    sleep 10
    sudo python /opt/LCDcontroller/scrollText.py &
    ;;
  stop)
    echo "Stopping LCD-controller "
    sudo killall python
    ;;
  restart)
    echo "Restarting LCD-controller"
    sudo killall python
    sudo python /opt/LCDcontroller/scrollText.py &
    ;;
  *)
    echo "Usage: /etc/init.d/volumioLCDservice {start|stop}"
    exit 1
    ;;
esac

exit 0
